filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

output.logstash:
  hosts: ["logstash:5044"]
  bulk_max_size: 128

queue.mem:
  events: 1024
  flush.min_events: 128
  flush.timeout: 0s

logging.level: info
logging.to_files: false
logging.to_stderr: true
