input {
  beats {
    port => 5044
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "suricata-%{+YYYY.MM.dd}"
  }

  redis {
    host => "redis"
    port => 6379
    key => "suricata"
    data_type => "channel"
  }
}
